echo "Analysis started"

echo "strdb_score (100-900) file already generated by R"

echo "Getting no-self for different genomic bins"
for genomic_bins in 400
do
	for hotspot_cutoff in 10 25 50 100
	do
		awk '{if($1!=$2) print $0}' gbin_${genomic_bins}_total_sites_bound_summit_hsrfree_mat_st_pois_re_${hotspot_cutoff}.txt > gbin_${genomic_bins}_total_sites_bound_summit_hsrfree_${hotspot_cutoff}_mat_st_pois_re_noself.txt
		sort -k1,1 -k2,2n gbin_${genomic_bins}_total_sites_bound_summit_hsrfree_${hotspot_cutoff}_mat_st_pois_re_noself.txt > gbin_${genomic_bins}_total_sites_bound_summit_hsrfree_${hotspot_cutoff}_mat_st_pois_re_noself_sorted.txt
	done
done

echo "Benchmarking with strinDB"
for strdb_score in 100 200 300 400 500 600 700 800 900
do
	for genomic_bins in 200 400 600 800 1000 10000 100000 1000000
	do
		for hotspot_cutoff in 10 25 50 100
		do
			echo "${strdb_score}, ${genomic_bins}, ${hotspot_cutoff}"
			echo "Filtering for proteins matched between ENCODE (${genomic_bins})  and stringDB (${strdb_score}).."
			echo "Executing script stringDB_complex_count_filter.py.."
			python3 ./scripts/stringDB_complex_count_filter.py 9606.protein.info.v12.0.txt 9606.protein_id_links_${strdb_score}.txt gbin_${genomic_bins}_total_sites_bound_summit_hsrfree_${hotspot_cutoff}_mat_st_pois_re_noself.txt > protein_id_links_filtered_pois_${genomic_bins}_${strdb_score}_${hotspot_cutoff}.txt
			echo "Albhabetically sort both files i.e encode and stringDB (alphabetical sorting is must)"
			sort -k1,1 -k2,2n protein_id_links_filtered_pois_${genomic_bins}_${strdb_score}_${hotspot_cutoff}.txt > protein_id_links_filtered_pois_${genomic_bins}_${strdb_score}_${hotspot_cutoff}_sorted.txt
			echo "Performing Precison and Recall and F1-score Analysis.."
			echo "Executing script mod_matchmark_complexes.py.."
			python3 ./scripts/mod_matchmark_complexes.py protein_id_links_filtered_pois_${genomic_bins}_${strdb_score}_${hotspot_cutoff}_sorted.txt gbin_${genomic_bins}_total_sites_bound_summit_hsrfree_${hotspot_cutoff}_mat_st_pois_re_noself_sorted.txt > protein_id_links_filtered_pois_${genomic_bins}_${strdb_score}_${hotspot_cutoff}_sorted_prf.txt
		done
	done
done

echo "Removing temporary files"
rm -r protein_id_links_filtered_pois_${genomic_bins}_${strdb_score}_${hotspot_cutoff}.txt
rm -r gbin_${genomic_bins}_total_sites_bound_summit_hsrfree_${hotspot_cutoff}_mat_st_pois_re_noself.txt

echo "Analysis done"
